### PR TITLE
Fda environment selection

### PR DESCRIPTION
**Pull request by hradilm**

### CODE REVIEW

**Comment by hradilm** [comment]
Coding is done.
@vasicem, how do we communicated changes in the `appsetting.json` file

**Comment by mivasi** [comment]
> Coding is done.
> @vasicem, how do we communicated changes in the `appsetting.json` file

We can show the example of usage inside the template file.

**Comment by hradilm** [comment]
> > Coding is done.
> > @vasicem, how do we communicated changes in the `appsetting.json` file
> 
> We can show the example of usage inside the template file.

That is what I have thought. The problem is, we do not have template file. We have it mentioned it in the readme.md file and I do not want to expose it that much. So we would probably introduce the template file now and modify the readme.

**Comment by hradilm** [comment]
Work is done. Please review

**Review by mivasi — APPROVED** [review]

**Pull request merged**
