### PR TITLE
Switching to polling as default

### PR DESCRIPTION
**Pull request by hradilm**
Changing pipeline to run tests on the release build

### CODE REVIEW

**Review by erymski — APPROVED** [review]
Maybe some docs should be changed? @Dc41f

**Comment by Dc41f** [comment]
> Maybe some docs should be changed? @Dc41f

I will remove (Optional) flag from the setup step that explains callbacks and add (Optional) step to switch to polling

**Comment by hradilm** [comment]
Yes, thanks for the reminder. I wanted to do that but forgot.

**Comment by Dc41f** [comment]
@hradilm @erymski Please check the readme changes :)

**Comment by hradilm** [comment]
Actually I just reviewed the "master" version of readme.md file and it looks ok to me. It is already written in the way that polling is default. @Dc41f you just changed it, so it looks like default is callback (which is not :-))

**Comment by Dc41f** [comment]
> Actually I just reviewed the "master" version of readme.md file and it looks ok to me. It is already written in the way that polling is default. @Dc41f you just changed it, so it looks like default is callback (which is not :-))

Revert incoming, i saw changing default and my name mentioned and though its the other way around. Friday evening.. :D

**Pull request merged**
